### ISSUE TITLE
Add PAT with repo/project scope as secret

### ISSUE THREAD

**Issue by brandomr** [anandijain/SimulationService.jl#2]
Per [this guide](https://docs.google.com/document/d/1_RvLMZ3KZChyR02yn-EdeOJWi9QmdrzUPZYgxKp48Y4/edit#heading=h.6x8rkjwa8fzc) this issue is to add a PAT with repo/project scope as a secret on this repo called `ADD_TO_PROJECT_PAT`.

As a contributor to the repo I don't have access to the repo's settings.

**Comment by anandijain** [comment]
I didn't see a way to get admin access to you, but following the guide it seems like I need to be a member of DARPA-ASKEM. I'm happy to just transfer the repo now. If you invite me, I'll send over the transfer request

![image](https://user-images.githubusercontent.com/33790004/221300819-2da89f09-7a20-4b69-b24d-a77c8efe1a86.png)

**Comment by anandijain** [comment]
@brandomr small reminder to invite me to DARPA-ASKEM to complete this

**Comment by brandomr** [comment]
Done

**Comment by anandijain** [comment]
thanks
