### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by brandomr** [anandijain/SimulationService.jl#4]
We could probably largely use [this Dockerfile](https://github.com/DARPA-ASKEM/sim-service/blob/main/Dockerfile) and the corresponding `docker-compose.yaml`.

**Comment by anandijain** [comment]
I did the obvious name changes, but I don't know Docker all that well. I suspect that commit does all thats needed, but once I get the readme example we can have someone (perhaps me) test and close

**Comment by brandomr** [comment]
I can test this a bit
